---
- hosts: [ all ]
  gather_facts: yes
  pre_tasks:
    - name: "Update Ubuntu derivatives"
      tags: always
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_pkg_mgr == "apt"
      become: true

  roles:
    - { role: familyplanner, tags: [ 'familyplanner' ]}
  vars:
    wwwPath: "/var/www/html/arcticon.de/dev/"